server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: docker
  sa-token:
    token-name: token
    timeout: 2592000
    activity-timeout: -1
    allow-concurrent-login: false
    is-share: false
    token-style: uuid
    is-log: false
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/flomo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /
  redis:
    port: 6379
    host: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
sms:
  username: xxx
  password: xxx
qiniu:
  AK: xxx
  SK: xxx
  DOMAIN: xxx
  BUCKET: xxx
wechat:
  appName: xxx
  appId: xxx
  appSecret: xxx
  token: xxx